spring:
  application:
    name: Task Manager

  datasource:
    url: jdbc:mysql://localhost:3306/task_manager?createDatabaseIfNotExist=true
    username: root
    password: bikram123@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  flyway:
    enabled: true
    locations: classpath:db/migration

  jwt:
    secret: ${JWT_SECRET}
